# Generated by Django 4.2 on 2023-07-30 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Upload',
            new_name='UserUpload',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
