# Generated by Django 4.2 on 2023-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.URLField(null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
