# Generated by Django 4.2 on 2023-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_upload_userupload_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_uploads/'),
        ),
    ]
