# Generated by Django 4.2 on 2023-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_diseasedetail_delete_disease_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCareCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(null=True)),
            ],
        ),
    ]
