# Generated by Django 4.1.4 on 2023-06-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_skincarecenter_delete_skincarecenters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetail',
            name='images',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
