# Generated by Django 4.1.4 on 2023-06-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_diseasedetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetail',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
