# Generated by Django 4.1.4 on 2023-06-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_diseasedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='human.png', upload_to='userprofile'),
        ),
    ]
