# Generated by Django 4.2 on 2023-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='human.png', upload_to='userprofile/'),
        ),
    ]
