# Generated by Django 4.2 on 2023-07-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_disease_rename_images_diseasedetail_main_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUploadedImage',
        ),
    ]
