# Generated by Django 4.2 on 2023-07-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_affectedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='')),
                ('existing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.diseasedetail')),
            ],
        ),
    ]
