# Generated by Django 4.2 on 2023-07-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_diseaseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasedetail',
            old_name='images',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='diseasedetail',
            name='image',
        ),
    ]
