# Generated by Django 4.2 on 2023-07-28 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_user_uploads_delete_useruploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Uploads',
            new_name='User_Upload',
        ),
    ]
