# Generated by Django 4.2 on 2023-07-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_rename_user_uploads_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_upload',
            name='user',
        ),
        migrations.AddField(
            model_name='user_upload',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
